[project]
name = "fab-scraper-bot"
version = "0.1.0"
description = "Searches the online market for the cheapest Flesh and Blood cards and notifies you via Telegram"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "python-dotenv>=1.2.2",
    "python-telegram-bot>=22.6",
    "requests>=2.32.5",
]

[project.scripts]
bot = "bot.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.workspace]
members = [
    "dotenv",
]
